"""Read linking-v2 anchor pool and apply anchor competition rule.

Provides candidate internal links per topic and checks anchor text against
the sitewide internal keyword set. Returns empty lists (not errors) when
anchor pool is empty — articles generate without links, validator warns.

See docs/article-spec.md Section 11 for anchor text rules.
See docs/v2-module-architecture.md "lib/anchor_pool.py" for API contract.
"""

# SHAPE_NOTES — verified against modules/linking-v2/ source code:
#
# Anchor pool file: sites/{site_slug}-anchor-pools.json
# Generated by: modules/linking-v2/tools/generate-anchor-pool.sh
#
# JSON shape:
# {
#   "site": str,
#   "generated_at": str (ISO 8601),
#   "ai_provider": str,
#   "ai_model": str,
#   "destinations": [
#     {
#       "id": int,
#       "url": str,
#       "slug": str,
#       "title": str,
#       "primary_keyword": str,
#       "anchors": [str, ...],        # 20-25 anchor text variations
#       "anchor_count": int,
#       "generated_at": str,
#       "usage": {prompt_tokens, completion_tokens, total_tokens}
#     }
#   ],
#   "stats": {total_destinations, successful, failed, ...}
# }
#
# The pool contains ALL destination pages for the site, each with
# AI-generated anchor text variations. The primary_keyword field
# drives the internal keyword set for anchor competition checks.

import json
import re
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent


@dataclass
class AnchorCandidate:
    url: str
    anchor_text: str
    topic_match_score: float  # 0.0 - 1.0
    usage_count_sitewide: int


class AnchorPool:
    """Anchor pool reader with topic matching and competition checking.

    Args:
        site_slug: Site identifier (e.g., 'lrg', 'valn').
    """

    def __init__(self, site_slug: str):
        self.site_slug = site_slug
        self._destinations: list[dict] = []
        self._internal_keywords: set[str] | None = None
        self._site_domain: str = ""
        self._loaded = False
        self._load_site_domain()
        self._load_pool()

    def _load_site_domain(self) -> None:
        """Load SITE_DOMAIN from site config for URL normalization."""
        try:
            from lib.site_config import load_site_config
            config = load_site_config(self.site_slug)
            self._site_domain = config.get("SITE_DOMAIN", "")
        except (FileNotFoundError, Exception):
            pass

    def _normalize_url(self, url: str) -> str:
        """Convert same-domain absolute URLs to relative paths."""
        if not self._site_domain or not url:
            return url
        parsed = urlparse(url)
        host = parsed.netloc.lower().lstrip("www.")
        if host == self._site_domain.lower().lstrip("www."):
            return parsed.path or "/"
        return url

    def _load_pool(self) -> None:
        """Load the anchor pool JSON. Gracefully handles missing file."""
        pool_path = REPO_ROOT / "sites" / f"{self.site_slug}-anchor-pools.json"
        if not pool_path.exists():
            self._loaded = True
            return

        try:
            with open(pool_path) as f:
                data = json.load(f)
            self._destinations = data.get("destinations", [])
            self._loaded = True
        except (json.JSONDecodeError, KeyError):
            self._loaded = True

    def candidates_for_topic(self, topic: str, max: int = 5, exclude_post_id: int | None = None) -> list[AnchorCandidate]:
        """Find internal link candidates matching a topic.

        Uses keyword overlap between the topic and each destination's
        primary_keyword + anchors. Returns up to `max` candidates sorted
        by match score descending.

        Args:
            topic: The subtopic to find links for (e.g., "VA funding fee exemptions").
            max: Maximum candidates to return.
            exclude_post_id: If set, skip destinations matching this post ID
                (prevents an article from linking to itself).

        Returns:
            List of AnchorCandidate, empty if pool not loaded/seeded.
        """
        if not self._destinations:
            return []

        topic_lower = topic.lower()
        topic_words = set(re.findall(r"[a-z]+(?:'[a-z]+)?", topic_lower))

        scored: list[AnchorCandidate] = []
        for dest in self._destinations:
            # Self-link prevention
            if exclude_post_id is not None and dest.get("id") == exclude_post_id:
                continue

            primary_kw = dest.get("primary_keyword", "").lower()
            anchors = dest.get("anchors", [])
            url = dest.get("url", "")

            # Score against primary keyword
            kw_words = set(re.findall(r"[a-z]+(?:'[a-z]+)?", primary_kw))
            if not kw_words:
                continue
            overlap = topic_words & kw_words
            base_score = len(overlap) / len(topic_words) if topic_words else 0.0

            if base_score < 0.2:
                continue

            # Find best anchor text for this topic
            best_anchor = primary_kw
            best_anchor_score = base_score
            for anchor in anchors:
                anchor_lower = anchor.lower()
                anchor_words = set(re.findall(r"[a-z]+(?:'[a-z]+)?", anchor_lower))
                anchor_overlap = topic_words & anchor_words
                anchor_score = len(anchor_overlap) / len(topic_words) if topic_words else 0.0
                if anchor_score > best_anchor_score:
                    best_anchor = anchor
                    best_anchor_score = anchor_score

            scored.append(AnchorCandidate(
                url=self._normalize_url(url),
                anchor_text=best_anchor,
                topic_match_score=round(min(best_anchor_score, 1.0), 3),
                usage_count_sitewide=0,  # not tracked yet
            ))

        scored.sort(key=lambda c: c.topic_match_score, reverse=True)
        return scored[:max]

    def is_internal_anchor_keyword(self, anchor_text: str) -> bool:
        """Check if anchor text collides with a sitewide internal anchor keyword.

        Per spec Section 11.3: external anchor text MUST NOT use the same
        topical keywords that internal anchors use sitewide.

        Args:
            anchor_text: The candidate external link anchor text.

        Returns:
            True if the anchor text matches an internal keyword (collision).
        """
        internal_kws = self.get_internal_keywords_set()
        if not internal_kws:
            return False
        return anchor_text.lower().strip() in internal_kws

    def get_internal_keywords_set(self) -> set[str]:
        """Build the sitewide set of internal anchor keywords.

        Derived from each destination's primary_keyword field.
        Used for anchor competition checks per spec Section 11.3.

        Returns:
            Set of lowercase keyword strings, empty if pool not loaded.
        """
        if self._internal_keywords is None:
            self._internal_keywords = set()
            for dest in self._destinations:
                kw = dest.get("primary_keyword", "").strip()
                if kw:
                    self._internal_keywords.add(kw.lower())
        return self._internal_keywords
